name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: When I call `app.scope(...)`, I get an unexpected error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Minimal code to reproduce the issue. The simpler, the faster we can fix it.
      render: typescript
      placeholder: |
        import { container } from 'inwire';

        const app = container()
          .add('foo', () => 'bar')
          .build();

        // This throws unexpectedly:
        app.foo;
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What happened instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: inwire version
      placeholder: "2.1.1"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      options:
        - Node.js
        - Deno
        - Bun
        - Cloudflare Workers
        - Browser
        - Other
    validations:
      required: true

  - type: input
    id: runtime-version
    attributes:
      label: Runtime version
      placeholder: "Node.js 22.0.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else that might help (error messages, stack traces, screenshots).
