name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the use case?
      placeholder: I often need to... but currently inwire doesn't support...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work? Code examples are welcome.
      render: typescript
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've thought about?

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area of inwire does this affect?
      options:
        - Container API
        - Type inference
        - Error handling
        - Introspection
        - Lifecycle (onInit/onDestroy)
        - Scopes
        - Modules
        - Documentation
        - Tooling / CI
        - Other
    validations:
      required: true
